In [1]:
import numpy as np
import pandas as pd

In [2]:
for i in range(len(pd.read_csv('final_is_area.csv').values)):  # 循环几个内标
    print(i)
    input_data1 = pd.read_csv('final_area.csv').values  # 读文件 不包含header
    input_data2 = pd.read_csv('final_is_area.csv').values  # 读文件 不包含header
    col = pd.read_csv('final_area.csv',header=None).values[1:,0:2]  # 前两列数据(去除第一行)
    row = pd.read_csv('final_area.csv',header=None).values[0,:]  # 第一行行名
    feature = input_data2[i,0:1]  # 获取IS内标名称 组成生成的文件名
    feature = feature[0]
    print("feature----------", feature)
    input_data1 = input_data1[0:,2:]  # 纯数据
    input_data2 = input_data2[i,2:]  # 纯数据(一行IS内标值)
    print("input_data1----------", input_data1)
    print("input_data2----------", input_data2)

    res = np.divide(input_data1,input_data2)  # 做矩阵除法
    res = np.column_stack((col,res))  # 合并列
    res = np.row_stack((row,res))  # 合并行
    print("res----------", res)
    filename = 'final_is_ratio_' + feature +  '.csv'  # 组成生成的文件名
    np.savetxt(filename, res, fmt='%s', delimiter=',')  # numpy.array写文件


0
feature---------- Luopaikayin_1
input_data1---------- [[8416.0 422603.0 132733.0 ... 264722.0 203373.0 163625.0]
 [193826.0 240927.0 130333.0 ... 239626.0 258154.0 321879.0]
 [315457.0 366956.0 339957.0 ... 411674.0 331688.0 398917.0]
 ...
 [4259.0 2430.0 3853.0 ... 3988.0 5746.0 9855.0]
 [5746.0 4658.0 6885.0 ... 5814.0 12540.0 19097.0]
 [10275.0 9329.0 14568.0 ... 9011.0 17880.0 34679.0]]
input_data2---------- [3691488 3678155 3734061 3716276 3696051 4004261 3718370 3531731 3620440
 3564331 3276068 3611371 3606608 3098623 3622972 3251041 3415494 3268033
 3682395 3747140 3369802 2843515 3786223 3293610 3794106 3427602 3338917
 3377251 3403048 2757696 3431738 3503831 3472435 3318929 2942838 3256762
 3042305 3208705 3404092 3305607 3350351 3497142 3664698 3110048 3621981
 2976280 3646216 3336758 3516597 3147728 3247838 2982879 2863982 3140333
 3479653 3162305 3193853 3038965 2906412 2991981 2729334 3132408 3397183
 3237431 1482778 3861610 3223505 2825079]
res---------- [['first' nan '