### 计算批内 Ipooled_CV -- > final_Ipooled_CV.csv


In [18]:
import numpy as np
import pandas as pd
input_data = pd.read_csv('final_area.csv').values  # 读文件 不包含header
# 必须添加header=None，否则默认把第一行数据处理成列名删除导致缺失
col = pd.read_csv('final_area.csv',header=None).values[1:,0:2]  # 前两列数据(去除第一行)
row = pd.read_csv('final_area.csv',header=None).values[0,:]  # 第一行行名

In [19]:
# 数据预处理
input_data = input_data[0:,2:]  # 纯数据
input_data = np.array(input_data,dtype=np.float32)
input_data = np.nan_to_num(input_data, nan=0)  # 将空值赋值为0
ISBLK = input_data[0:,-4]  # ISBLK
input_data = (input_data.T - ISBLK).T  # 所有列减去ISBLK
input_data = np.maximum(input_data, 0)  # 将小于0的置为0

yx01Ipooled = input_data[0:,-3:]
print("yx01Ipooled----------", yx01Ipooled)

yx01Ipooled---------- [[2.6228800e+05 2.0093900e+05 1.6119100e+05]
 [1.1858800e+05 1.3711600e+05 2.0084100e+05]
 [2.8325800e+05 2.0327200e+05 2.7050100e+05]
 [2.4705300e+05 3.2176600e+05 1.7225400e+05]
 [9.8699000e+04 1.2800800e+05 1.2858200e+05]
 [3.2007370e+06 2.9969260e+06 2.3584140e+06]
 [1.0781400e+05 9.8114000e+04 1.3705100e+05]
 [1.7902200e+05 1.1071200e+05 1.5495600e+05]
 [1.3827700e+05 9.9406000e+04 1.3023200e+05]
 [2.0790000e+04 2.1091000e+04 1.7103000e+04]
 [1.5987000e+04 1.4331000e+04 1.3249000e+04]
 [3.3327000e+04 3.2433000e+04 2.8426000e+04]
 [3.2805000e+04 2.7675000e+04 2.4405000e+04]
 [0.0000000e+00 1.2480000e+03 2.2520000e+03]
 [7.2330000e+03 7.0980000e+03 6.6920000e+03]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [1.7878550e+06 1.9316000e+06 1.6678880e+06]
 [2.0702600e+05 1.8846900e+05 1.8150600e+05]
 [9.1950000e+03 1.2777000e+04 1.1425000e+04]
 [3.3409600e+05 2.8826300e+05 3.4105900e+05]
 [2.1069300e+05 2.0151200e+05 2.4932700e+05]
 [8.0379000e+04 7.0103000e+04 6.5

In [20]:
# 计算批内 Ipooled_CV
std = np.std(yx01Ipooled,axis=1)  # 计算标准差
mean = np.mean(yx01Ipooled,axis = 1) # 计算平均数
Ipooled_CV = (std/mean) * 100  # 计算cv
print("Ipooled_CV----------", Ipooled_CV)

# 组织最终输出数据的格式 给计算结果附上列名
row = np.concatenate((row,['Ipooled_CV']))  # 给原有的列名增加一列
res = np.column_stack((col,input_data,Ipooled_CV))  # 合并列
res1 = np.row_stack((row,res))
res1 = np.delete(res1, -5, axis=1)
res1

Ipooled_CV---------- [ 19.979658   23.14928    13.9046755  24.709316   11.78223    12.581116
  14.475693   19.085262   13.660361    9.222079    7.753174    6.7880177
  12.218396   78.95762     3.2808855         nan   6.003279    5.6001263
  13.266905    7.292856    9.395502    8.391255    3.919881   27.475088
 141.42137    14.542624  141.42137    18.645353    7.4720054   7.68639
  11.402336    3.5799668         nan  51.40278   141.42136     6.5672464
   4.2530966   2.1013706   3.1162572   6.5258636  27.722172   67.73855
         nan         nan  12.763077    7.8693666   7.239639    5.157552
   6.500191    3.4644036   8.265989   14.4927845  25.30748    10.597913
   5.060896    5.5959044   5.370824    3.4942646   2.03747     3.1475742
   1.4789325   2.9670615   8.462475    4.2591      7.1263814 141.42137
  17.61621     5.542991    5.2315874  31.720976   87.394455   21.564129
  49.32956     7.8955016  20.121319    9.045889    5.733412  112.4489
   5.432192   39.705914   45.150764   51.864

<ipython-input-20-034a237f2fae>:4: RuntimeWarning: invalid value encountered in true_divide
  Ipooled_CV = (std/mean) * 100  # 计算cv


array([['first', nan, 'yx0201', ..., 'yx02Ipooled_2', 'yx02Ipooled_3',
        'Ipooled_CV'],
       ['4.66_195.0870-1', 'Area', 5982.0, ..., 200939.0, 161191.0,
        19.979658126831055],
       ['X10.06_547.3433-1', 'Area', 72788.0, ..., 137116.0, 200841.0,
        23.149280548095703],
       ...,
       ['X9.74_333.1467-1', 'Area', 3921.0, ..., 5408.0, 9517.0,
        39.70591354370117],
       ['X9.74_333.1467-2', 'Area', 5273.0, ..., 12067.0, 18624.0,
        45.15076446533203],
       ['X9.74_333.1467-3', 'Area', 10275.0, ..., 17880.0, 34679.0,
        51.86442184448242]], dtype=object)

In [21]:
np.savetxt('final_Ipooled_CV.csv', res1, fmt='%s', delimiter=',')  # numpy.array写文件